apiVersion: v1
kind: Service
metadata:
  name: shop-service
spec:
  selector:
    app: shop-service
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 31001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-service
spec:
  selector:
    matchLabels:
      app: shop-service
  replicas: 1
  template:
    metadata:
      labels:
        app: shop-service
    spec:
      containers:
        - name: server
          image: katerinamayevska/shop-service:latest
          ports:
            - name: http
              containerPort: 8081
---


